package org.example.petlocation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2
 * 2016-03-13T15:32:35.081-05:00
 * Generated source version: 3.1.2-jbossorg-2
 * 
 */
@WebService(targetNamespace = "http://www.example.org/PetLocation/", name = "PetLocation")
@XmlSeeAlso({ObjectFactory.class})
public interface PetLocation {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "receiveLocation", targetNamespace = "http://www.example.org/PetLocation/", className = "org.example.petlocation.ReceiveLocation")
    @WebMethod(action = "http://www.example.org/PetLocation/receiveLocation")
    @ResponseWrapper(localName = "receiveLocationResponse", targetNamespace = "http://www.example.org/PetLocation/", className = "org.example.petlocation.ReceiveLocationResponse")
    public java.lang.String receiveLocation(
        @WebParam(name = "latitud", targetNamespace = "")
        java.lang.String latitud,
        @WebParam(name = "longitud", targetNamespace = "")
        java.lang.String longitud,
        @WebParam(name = "frecuenciaCardiaca", targetNamespace = "")
        java.lang.String frecuenciaCardiaca,
        @WebParam(name = "frecuenciaRespiratoria", targetNamespace = "")
        java.lang.String frecuenciaRespiratoria,
        @WebParam(name = "idCollar", targetNamespace = "")
        java.lang.String idCollar
    );
}
