package org.example.petlocation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2-jbossorg-2
 * 2016-03-13T15:32:35.090-05:00
 * Generated source version: 3.1.2-jbossorg-2
 * 
 */
@WebServiceClient(name = "PetLocation", 
                  wsdlLocation = "file:/home/emunoz/workspace_8/gps-pet/src/main/resources/PetLocation.wsdl",
                  targetNamespace = "http://www.example.org/PetLocation/") 
public class PetLocation_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/PetLocation/", "PetLocation");
    public final static QName PetLocationSOAP = new QName("http://www.example.org/PetLocation/", "PetLocationSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/emunoz/workspace_8/gps-pet/src/main/resources/PetLocation.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PetLocation_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/emunoz/workspace_8/gps-pet/src/main/resources/PetLocation.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PetLocation_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PetLocation_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PetLocation_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PetLocation_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PetLocation_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PetLocation_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PetLocation
     */
    @WebEndpoint(name = "PetLocationSOAP")
    public PetLocation getPetLocationSOAP() {
        return super.getPort(PetLocationSOAP, PetLocation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PetLocation
     */
    @WebEndpoint(name = "PetLocationSOAP")
    public PetLocation getPetLocationSOAP(WebServiceFeature... features) {
        return super.getPort(PetLocationSOAP, PetLocation.class, features);
    }

}
